version: "3.0"

services: 
    node:
        container_name: tdd_example
        image: tdd_example:1.0.3
        restart: always
        stdin_open: true
        tty: true
        links:
            - mongodb
        ports: 
            - "8080:8080"
        depends_on: 
            - mongodb
        volumes: 
            - /Data01/Project/tdd_example:/usr/src/app
    mongodb:
        container_name: mongodb
        image: mongo
        restart: always
        ports: 
            - "27017:27017"
